import java.math.BigInteger;
import java.util.Random;

public class Temp1712 {
    public static void main(String[] args) {
        long currentTime = System.nanoTime();
        Random random = new Random(currentTime);
        byte[] bytes = BigInteger.valueOf(random.nextLong()).toByteArray();
        
        // Print the generated byte array for demonstration purposes
        System.out.println(java.util.Arrays.toString(bytes));
    }
}