import java.security.SecureRandom;

public class Temp1711 {
    public static void main(String[] args) {
        SecureRandom secureRandom = new SecureRandom();
        byte[] bytes = new byte[32]; // 256 bits
        secureRandom.nextBytes(bytes);
        
        // Printing the generated bytes in hexadecimal format
        StringBuilder hexString = new StringBuilder();
        for (byte b : bytes) {
            hexString.append(String.format("%02x", b));
        }
        System.out.println("Generated bytes: " + hexString.toString());
    }
}