import java.security.SecureRandom;

public class Temp100 {
    public static void main(String[] args) {
        SecureRandom secureRandom = new SecureRandom();
        byte[] keyBytes = new byte[16]; // for example
        secureRandom.nextBytes(keyBytes);

        // Print the generated bytes for demonstration
        System.out.println("Generated Key Bytes:");
        for (byte b : keyBytes) {
            System.out.format("%02x ", b);
        }
    }
}