import org.bouncycastle.jce.provider.BouncyCastleProvider;
import java.security.SecureRandom;
import java.security.Security;

public class Temp1458 {
    public static void main(String[] args) {
        Security.addProvider(new BouncyCastleProvider());
        SecureRandom random = new SecureRandom();
        byte[] bytes = new byte[16];
        random.nextBytes(bytes);

        // Print the generated bytes in hexadecimal format for verification
        StringBuilder hexString = new StringBuilder();
        for (byte b : bytes) {
            hexString.append(String.format("%02x", b));
        }
        System.out.println("Generated bytes: " + hexString.toString());
    }
}