SELECT * 
FROM (
  SELECT 
    t1.CHARACTER_SET_NAME AS cs1, 
    t2.CHARACTER_SET_NAME AS cs2, 
    t3.CHARACTER_SET_NAME AS cs3, 
    t4.CHARACTER_SET_NAME AS cs4, 
    t5.CHARACTER_SET_NAME AS cs5, 
    t6.CHARACTER_SET_NAME AS cs6
  FROM 
    CHARACTER_SETS t1, 
    CHARACTER_SETS t2, 
    CHARACTER_SETS t3, 
    CHARACTER_SETS t4, 
    CHARACTER_SETS t5, 
    CHARACTER_SETS t6
) AS t 
ORDER BY 1;