USE master;
GO

ALTER AUTHORIZATION ON DATABASE::A TO DatabaseOwnerLogin;
GO

ALTER AUTHORIZATION ON DATABASE::B TO DatabaseOwnerLogin;
GO

ALTER AUTHORIZATION ON DATABASE::C TO DatabaseOwnerLogin;
GO

ALTER AUTHORIZATION ON DATABASE::D TO DatabaseOwnerLogin;
GO

ALTER AUTHORIZATION ON DATABASE::E TO DatabaseOwnerLogin;
GO