SELECT *
FROM your_table
WHERE (SYS_CONTEXT('USERENV', 'CURRENT_USER') = 'BOB' AND salary > 1000)
   OR (SYS_CONTEXT('USERENV', 'CURRENT_USER') = 'ANNE' AND salary < 1000)
   OR (SYS_CONTEXT('USERENV', 'CURRENT_USER') NOT IN ('BOB', 'ANNE'));