x = bytes(bytearray.fromhex('f3'))
print(x)
print(len(x))
print(str(x))
print(len(str(x)))
print(x == str(x))
print(str(x).encode())
print(x == str(x).encode())
print(eval(str(x)))
print(x == eval(str(x)))