xml
<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>
    /WEB-INF/groceryapp-servlet.xml,
    /WEB-INF/spring-security.xml,
    /WEB-INF/classes/MySQL_DataSource.xml
  </param-value>    
</context-param>