CREATE DATABASE database_name;
GO

USE database_name;
GO

CREATE VIEW view_name
AS SELECT 1 AS Test
WITH CASCADED CHECK OPTION;
GO

ALTER VIEW view_name
AS SELECT 1 AS Test
WITH CASCADED CHECK OPTION
SQL SECURITY INVOKER;
GO